# Generated by Django 4.1.1 on 2022-09-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applatsar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasegempa',
            name='stasiun_id',
        ),
        migrations.AddField(
            model_name='databasegempa',
            name='stasiun',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Stasiun',
        ),
    ]
