# Generated by Django 4.1.1 on 2022-10-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applatsar', '0002_remove_databasegempa_stasiun_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasegempa',
            name='magnitudo',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
