# Generated by Django 4.1.1 on 2022-10-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applatsar', '0003_alter_databasegempa_magnitudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasegempa',
            name='bujur',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='databasegempa',
            name='jam',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='databasegempa',
            name='lintang',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='databasegempa',
            name='stasiun',
            field=models.CharField(choices=[('BMKG-PGR1', 'BMKG-PGR1'), ('BMKG-TPTI', 'BMKG-TPTI'), ('BMKG-TSI', 'BMKG-TSI'), ('BMKG-GSI', 'BMKG-GSI'), ('BMKG-BSI', 'BMKG-BSI')], default='2', max_length=20, null=True),
        ),
    ]
