# Generated by Django 4.1.1 on 2022-10-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applatsar', '0004_alter_databasegempa_bujur_alter_databasegempa_jam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseTamu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30, null=True)),
                ('tanggal', models.DateField(null=True)),
                ('instansi', models.CharField(max_length=30, null=True)),
                ('agenda', models.TextField(max_length=30, null=True)),
            ],
        ),
    ]
