# Generated by Django 4.1.1 on 2022-10-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applatsar', '0005_databasetamu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasetamu',
            name='agenda',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='databasetamu',
            name='tanggal',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
