# Generated by Django 4.1.1 on 2022-10-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applatsar', '0007_alter_databasetamu_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasetamu',
            name='jam',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='databasetamu',
            name='tanggal',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
